### ISSUE TITLE
centos7.9+python3.8.8+openlava-4.0.0环境，只有部分bsample能顺利执行

### ISSUE THREAD

**Issue by xaisc** [liyanqing1987/lsfMonitor#5]
您好！在centos7.9+python3.8.8+openlava4的环境里运行出错
手动执行bsample命令发现，bsample -j和bsample -q这两个命令执行出错，bmonitor也无法启动
其他的bsample命令可以正常执行，并在db目录下生成数据
![cb325f9f8ac922edf0c9e84a61d04be](https://github.com/user-attachments/assets/4438cc01-5701-4dd1-b597-0c042e6831a3)
![bdc3e5214c2ac2ec65c290842c85a5c](https://github.com/user-attachments/assets/8eae7c5d-a87a-4f0f-b8d5-f49e9efe848b)

另外python换成3.6.8，lsfmonitor换成旧版的openlavamonitor的话，可以正常的获取全部信息，并通过gui界面显示出来。

**Comment by liyanqing1987** [comment]
已解决，请用最新版patch一下再试试。

**Comment by xaisc** [comment]
> 已解决，请用最新版patch一下再试试。

没问题了，已经可以正常运行了
